### ISSUE TITLE
About grid step

### ISSUE THREAD

**Issue by DrikoldLun** [NoiseCIEI/RayTomo#1]
Hi, I'm a student in Geophysics major, and I'm trying to use your code here to conduct the ambient noise tomography for my research.  The minimum limit of the grid step (1°) is mentioned in the menu, and I have found the grid step of initial 2D model can't be set below 1° as well. I want to know if there is any way to reduce the grid size for higher resolution (especially for the high-frequency component)?  I will be so  appreciate if you can help me.

**Comment by ghraecakter** [comment]
Thanks for the feedback.

Please try the updated version 8b9b7c216485cb2d23450991d23fb8323e24f21b.

Best,
Shane

**Comment by DrikoldLun** [comment]
The updated version solved my problem perfectly, thanks!
